### ISSUE TITLE
Set Up Password Page Footer Is In The Way

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2353]
### Impacted User Types
 - volunteers
 - supervisors
 - admins

### Environment
Production

### Current Behavior
When I try to set the password on a new user, the page draws in such a way as to obscure the set password fields.
![Acceptin Invitation Update](https://user-images.githubusercontent.com/7007647/128121137-09c51d8b-f596-43c9-87aa-6264672cb674.png)

### Expected Behavior
When a new user attempts to set their password, the password fields should be visible/accessible. 

### How to Replicate
1. - Log into your local environment as an admin.
2. - Create a user.
3. - Click the "Set Your Password" prompt in the email.

**Comment by FireLemons** [comment]
The footer wasn't always like this. I suspect someone fixed something and broke this. It would be nice to have both things fixed

**Comment by scottolsen** [comment]
Looks like it was broken in #2113. I made the below changes and the password box is now viewable if the height of the device is under ~700px but the footer doesn't float to the bottom. 

```scss
// app/javascript/src/stylesheets/pages/password.scss

.password-box {
  width: 90%;
}

body.devise-invitations.devise-invitations-edit footer {
  // position: absolute;
}
```

<img width="445" alt="CleanShot 2021-09-19 at 07 53 38@2x" src="https://user-images.githubusercontent.com/113754/133928248-defa50bb-8231-421f-afc6-7ab41676ee2e.png">
<img width="441" alt="CleanShot 2021-09-19 at 07 54 11@2x" src="https://user-images.githubusercontent.com/113754/133928264-3256f695-4674-4fff-b5e4-0f0523537c49.png">
