### ISSUE TITLE
Bug: Flaky Test Massive System Test Failure

### ISSUE THREAD

**Issue by FireLemons** [rubyforgood/casa#5124]
Flaky tests are defined as tests that return both passes and failures despite no changes to the code or the test itself
Fix the test so it runs consistently.

Something is causing all the system tests to fail on some docker runs.

### CI Workflow
rspec in docker

### Sample Error Output:
```
 124.2) Failure/Error: Unable to infer file and line number from backtrace

              Selenium::WebDriver::Error::InvalidSessionIdError:
                invalid session id
              # #0 0x5556fee708f3 <unknown>
              # #1 0x5556fe955a3f <unknown>
              # #2 0x5556fe97e9cb <unknown>
              # #3 0x5556fe9a8dec <unknown>
              # #4 0x5556fe9a6b12 <unknown>
              # #5 0x5556fe9a6347 <unknown>
              # #6 0x5556fe92d774 <unknown>
              # #7 0x5556fe92e5a0 <unknown>
              # #8 0x5556fee9fc3e <unknown>
              # #9 0x5556feeb56b7 <unknown>
              # #10 0x5556feea0b95 <unknown>
              # #11 0x5556feeb6b05 <unknown>
              # #12 0x5556fee952ab <unknown>
              # #13 0x5556fe92d300 <unknown>
              # #14 0x7fb76e4cf0b3 __libc_start_main
              # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/response.rb:55:in `assert_ok'
              # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
              # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
              # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
              # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/http/default.rb:103:in `request'
              # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
              # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/bridge.rb:620:in `execute'
              # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/bridge.rb:267:in `screenshot'
              # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/driver.rb:339:in `screenshot'
              # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/takes_screenshot.rb:54:in `screenshot_as'
              # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/takes_screenshot.rb:56:in `screenshot_as'
              # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/takes_screenshot.rb:39:in `block in save_screenshot'
              # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/takes_screenshot.rb:39:in `open'
              # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/takes_screenshot.rb:39:in `save_screenshot'
              # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/selenium/driver.rb:161:in `save_screenshot'
              # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/session.rb:747:in `block in save_screenshot'
              # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/session.rb:747:in `save_screenshot'
              # /usr/local/bundle/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

 414) ReimbursementDatatable multiple record handling order by case number explicit ascending order should order correctly
       Failure/Error:
         create(
           :case_contact,
           casa_case: casa_case,
           occurred_at: Time.new - possible_occurred_at_offsets.pop,
           miles_driven: possible_miles_driven_values.pop
         )

       ActiveRecord::RecordInvalid:
         Validation failed: Occurred at cannot be in the future
       # /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/evaluation.rb:18:in `create'
       # /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/strategy/create.rb:12:in `block in result'
       # /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/strategy/create.rb:9:in `result'
       # /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/factory.rb:43:in `run'
       # /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/factory_runner.rb:29:in `block in run'
       # /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/factory_runner.rb:28:in `run'
       # /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/strategy_syntax_method_registrar.rb:28:in `block in define_singular_strategy_method'
       # ./spec/datatables/reimbursement_datatable_spec.rb:116:in `block (5 levels) in <top (required)>'
       # ./spec/datatables/reimbursement_datatable_spec.rb:115:in `times'
       # ./spec/datatables/reimbursement_datatable_spec.rb:115:in `each'
       # ./spec/datatables/reimbursement_datatable_spec.rb:115:in `collect'
       # ./spec/datatables/reimbursement_datatable_spec.rb:115:in `block (4 levels) in <top (required)>'
       # ./spec/datatables/reimbursement_datatable_spec.rb:113:in `times'
       # ./spec/datatables/reimbursement_datatable_spec.rb:113:in `each'
       # ./spec/datatables/reimbursement_datatable_spec.rb:113:in `collect'
       # ./spec/datatables/reimbursement_datatable_spec.rb:113:in `block (3 levels) in <top (required)>'
       # /usr/local/bundle/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

      90.4) Failure/Error: Unable to infer file and line number from backtrace

            Selenium::WebDriver::Error::InvalidArgumentError:
              invalid argument: 'handle' must be a string
                (Session info: headless chrome=94.0.4606.61)
            # #0 0x55d82ed1e8f3 <unknown>
            # #1 0x55d82e803ba8 <unknown>
            # #2 0x55d82e860067 <unknown>
            # #3 0x55d82e856e38 <unknown>
            # #4 0x55d82e82d144 <unknown>
            # #5 0x55d82e82e135 <unknown>
            # #6 0x55d82ed4dc3e <unknown>
            # #7 0x55d82ed636b7 <unknown>
            # #8 0x55d82ed4eb95 <unknown>
            # #9 0x55d82ed64b05 <unknown>
            # #10 0x55d82ed432ab <unknown>
            # #11 0x55d82ed7f248 <unknown>
            # #12 0x55d82ed7f3c8 <unknown>
            # #13 0x55d82ed9a33d <unknown>
            # #14 0x7ff1c9c36609 start_thread
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/response.rb:55:in `assert_ok'
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/http/default.rb:103:in `request'
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/bridge.rb:620:in `execute'
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/bridge.rb:168:in `switch_to_window'
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/target_locator.rb:107:in `window'
            # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/selenium/driver.rb:270:in `switch_to_window'
            # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/selenium/driver_specializations/chrome_driver.rb:40:in `reset!'
            # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/session.rb:131:in `reset!'
            # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara.rb:327:in `block in reset_sessions!'
            # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara.rb:327:in `reverse_each'
            # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara.rb:327:in `reset_sessions!'
            # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/rspec.rb:20:in `block (2 levels) in <top (required)>'
            # /usr/local/bundle/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

      90.2) Failure/Error: Unable to infer file and line number from backtrace

            Selenium::WebDriver::Error::NoSuchWindowError:
              no such window: target window already closed
              from unknown error: web view not found
                (Session info: headless chrome=94.0.4606.61)
            # #0 0x55d82ed1e8f3 <unknown>
            # #1 0x55d82e803ba8 <unknown>
            # #2 0x55d82e7e4702 <unknown>
            # #3 0x55d82e85a24b <unknown>
            # #4 0x55d82e869465 <unknown>
            # #5 0x55d82e856d63 <unknown>
            # #6 0x55d82e82d144 <unknown>
            # #7 0x55d82e82e135 <unknown>
            # #8 0x55d82ed4dc3e <unknown>
            # #9 0x55d82ed636b7 <unknown>
            # #10 0x55d82ed4eb95 <unknown>
            # #11 0x55d82ed64b05 <unknown>
            # #12 0x55d82ed432ab <unknown>
            # #13 0x55d82ed7f248 <unknown>
            # #14 0x55d82ed7f3c8 <unknown>
            # #15 0x55d82ed9a33d <unknown>
            # #16 0x7ff1c9c36609 start_thread
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/response.rb:55:in `assert_ok'
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/http/default.rb:103:in `request'
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/bridge.rb:620:in `execute'
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/remote/bridge.rb:267:in `screenshot'
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/driver.rb:339:in `screenshot'
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/takes_screenshot.rb:54:in `screenshot_as'
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/takes_screenshot.rb:56:in `screenshot_as'
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/takes_screenshot.rb:39:in `block in save_screenshot'
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/takes_screenshot.rb:39:in `open'
            # /usr/local/bundle/gems/selenium-webdriver-4.11.0/lib/selenium/webdriver/common/takes_screenshot.rb:39:in `save_screenshot'
            # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/selenium/driver.rb:161:in `save_screenshot'
            # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/session.rb:747:in `block in save_screenshot'
            # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/session.rb:747:in `save_screenshot'
            # /usr/local/bundle/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.
